#!/bin/bash
touch cscope.files
echo "" > cscope.files
for i in $@
do
    find $i -follow -name "*.cpp" >> cscope.files
    find $i -follow -name "*.c" >> cscope.files
    find $i -follow -name "*.h" >> cscope.files
    find $i -follow -name "*.hpp" >> cscope.files
    find $i -follow -name "*.lua" >> cscope.files
done
ctags --c++-kinds=+p --fields=+iaS --extra=+q -L cscope.files
ctags --langdef=MYLUA --langmap=MYLUA:.lua --regex-MYLUA="/^.*\s*function\s*(\w+):(\w+).*$/\2/f/" --regex-MYLUA="/^\s*(\w+)\s*=\s*[0-9]+.*$/\1/e/" --regex-MYLUA="/^.*\s*function\s*(\w+)\.(\w+).*$/\2/f/" --regex-MYLUA="/^.*\s*function\s*(\w+)\s*\(.*$/\1/f/" --regex-MYLUA="/^\s*(\w+)\s*=\s*\{.*$/\1/e/" --regex-MYLUA="/^\s*module\s+\"(\w+)\".*$/\1/m,module/" --regex-MYLUA="/^\s*module\s+\"[a-zA-Z0-9._]+\.(\w+)\".*$/\1/m,module/" --languages=MYLUA -N -L cscope.files -a tags
cscope -b -i cscope.files


